services:

  strom-reader:
    build: ./reader
    container_name: strom-reader
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./logs:/app/logs
      - /var/www/html:/app/data
    environment:
      - DEBUG=0
    restart: unless-stopped
    tty: true
    
  strom-dashboard:
    build: ./lighttpd
    container_name: strom-dashboard-frontend
    ports:
      - "8080:80"
    volumes:
      - /var/www/html:/var/www/localhost/htdocs:ro
  dashboard-backend:
    build: ./dashboard-backend
    container_name: strom-dashboard-backend
    ports:
      - "5000:5000"
    volumes:
      - /var/www/html/strom.sqlite:/app/data/strom.sqlite
