services:
  strom-raw-dump:
    build: .
    container_name: strom-raw-dump
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./logs:/app/logs
      - /usr/share/nginx/html:/app/data
    environment:
      - DEBUG=0
    restart: unless-stopped
    tty: true
