services:

  strom-dashboard-frontend:
    build: ./lighttpd
    container_name: strom-dashboard-frontend
    ports:
      - "8080:80"
    volumes:
      - /var/www/html:/var/www/localhost/htdocs:ro
    networks:
      - strom-network

  dashboard-backend:
    build: ./dashboard-backend
    container_name: strom-dashboard-backend
    ports:
      - "5000:5000"
    volumes:
      - /var/www/html/strom.sqlite:/app/data/strom.sqlite
    networks:
      - strom-network

networks:
  strom-network:
    driver: bridge
