services:

  strom-reader:
    build: .
    container_name: strom-reader-raw-dump
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./logs:/app/data/logs
    environment:
      - DEBUG=1
    restart: none
    tty: true
