services:

  strom-reader:
    build: .
    container_name: strom-reader
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./logs:/app/logs
      - /var/www/html:/app/data
    environment:
      - TZ=Europe/Berlin
      - BAUDRATE=9600 # Baudrate des Readers
      - MANUFACTORER=1 # 1 = EMH, 2 und höher aktuell nicht implementiert
      - DEBUG=0
      - WAIT-TIMER=60 # seconds, aller wieviele Sekunden soll der Reader die Daten schreiben
      - OUTPUT=sqlite # json,sqlite - kommagetrennt, mehrere Ausgabeformate werden in Zukunft implementiert
    restart: unless-stopped
    tty: true