services:

  strom-reader:
    build: .
    container_name: strom-reader
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./logs:/app/logs
      - /var/www/html:/app/data
    environment:
      - DEBUG=0
    restart: unless-stopped
    tty: true