services:

  strom-reader:
    build: .
    container_name: strom-reader
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./logs:/app/logs
      - .:/app/data
    environment:
      - BAUDRATE=9600 # Baudrate des Readers
      - MANUFACTORER=1 # 1 = EMH, 2 = Itron, 3 = Landis&Gyr 
      - DEBUG=1
      - WAIT-TIMER=60 # seconds, aller wieviele Sekunden soll der Reader die Daten schreiben
    restart: unless-stopped
    tty: true